{% set name = "randomgen" %}
{% set version = "1.20.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16f3866a7ddc0a2596b112153a7d170b828ef7d4228490604e86303930db3da5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.29
    - numpy
    - pip
    - python
    - setuptools
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - randomgen
  requires:
    - pytest
  commands:
    - python -c "import randomgen;randomgen.test(['--skip-slow'])"

about:
  home: https://github.com/bashtage/randomgen
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Numpy-compatible bit generators and add some random variate distributions missing from NumPy.
  description: |
    randomgen supplies many bit generators that can be used with numpy.random.Generator. It
    also supports additional variants of the bit generators included in NumPy.
  doc_url: https://bashtage.github.io/randomgen
  dev_url: https://bashtage.github.io/randomgen/devel


extra:
  recipe-maintainers:
    - duncanmmacleod
    - bashtage
