{% set name = "randomgen" %}
{% set version = "1.26.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1029fe65120631efbb42f9a78ee1a0fe6c17719ca034200675bc6061ed6fac1c

build:
  error_overlinking: true
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.33,<4                    # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - cython >=0.29.33,<4
    - numpy
    - packaging >=21.0
    - pip
    - python
    - setuptools
    - setuptools-scm
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  requires:
    - pip
    - pytest <8
    - pytest-xdist
    - scipy
  commands:
    # check requirements
    - python -m pip check
    # run test suite
    - python -c "import randomgen; randomgen.test(['--skip-slow', '--numprocesses', '{{ CPU_COUNT }}'])"

about:
  home: https://github.com/bashtage/randomgen
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Numpy-compatible bit generators and add some random variate distributions missing from NumPy.
  description: |
    randomgen supplies many bit generators that can be used with numpy.random.Generator. It
    also supports additional variants of the bit generators included in NumPy.
  doc_url: https://bashtage.github.io/randomgen
  dev_url: https://bashtage.github.io/randomgen/devel


extra:
  recipe-maintainers:
    - duncanmmacleod
    - bashtage
