{% set name = "randomgen" %}
{% set version = "1.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34e532ac08ac065303b64824e2411570f26832626d38b5402b87b4e989332892

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.26
    - numpy
    - pip
    - python
    - setuptools
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - randomgen
    - randomgen.legacy
  requires:
    - pytest
    - nose
  commands:
    - python -m pytest -rs --pyargs randomgen.tests

about:
  home: https://github.com/bashtage/randomgen
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Random generator supporting multiple PRNGs

extra:
  recipe-maintainers:
    - duncanmmacleod
